spring.application.name=microservicio-test-azure
server.port=8080
spring.security.oauth2.resourceserver.jwt.issuer-uri=https://login.microsoftonline.com/551e9396-e26d-4bf2-ba5b-baa0506d0cd9/v2.0
logging.level.org.springframework.security=DEBUG
logging.level.org.springframework.web=DEBUG
